### PR TITLE
Created installer and update script to automate installation of PiStorm

### PR DESCRIPTION
**Pull request by daniel-mrd-andersson**
To simplify the installation and update process for users that are not that Linux experience a scripts for installation and update is created included an readme on how to enable WiFi and SSH directly when writing Linux image to SD card. 

Added option to install Samba to ease the copying of files (roms/hdd images) to/from PiStorm Pi and also allowing for changes of config files via share.

PiStorm is added as a Linux service that starts when Pi is booted.

Script also install all needed decencies and updates the OS during installation.

### CODE REVIEW

**Comment by LemaruX** [comment]
You don't need to ask what version of PiStorm they have, as the revision is totally irrelevant. What matters is what CPLD is fitted as both rev A and rev B can use either EPM240 or EPM570. Your script as it stands, won't work if you have a Rev A with an EPM240 fitted. 

A better solution would be to use flash.sh, which has superceded nprog.sh, it will automatically detect the CPLD type and flash the correct bitstream. There is no need to use either of the nprog commands anymore.

**Comment by Blackbandit1804** [comment]
Hello,
I used the new linux_install script today that worked so far
but when I try a .hdf in the config I get this error

[PISCSI] Could not open PISCSI Boot ROM file for reading!

I get the same error with    setvar piscsi6 platforms/amiga/pistorm.hdf 

[AMIGA] PISCSI Interface Enabled.
[PISCSI] Could not open PISCSI Boot ROM file for reading!
Platform custom range: 00E80000-80010000
Platform mapped range: 00200000-72800000
[PISCSI] Failed to open file platforms/amiga/pistorm.hdf, could not map drive 6.

the path to the .hdf files are all corect

MfG
Blackbandit1804

**Comment by beeanyew** [comment]
@daniel-mrd-andersson 
This installer script can't possibly work.
You set the working directory to `/srv/pistorm`, but the data folder structure is not preserved there, and none of the necessary files from for instance the various `/platforms/amiga/` subdirectories are available there either. The RTG needs the shader files from `/platforms/amiga/rtg`, PiSCSI needs the boot ROM from /platforms/amiga/piscsi`, and there may be other relative paths used that I don't remember at the moment.

The PiStorm software is in active development, and running it from anywhere but the base directory where it is being built is not supported in any way. `default.cfg` will also be going away soon and get renamed to `amiga.cfg`. If you have any questions about what directory structures and files are needed at a minimum to provide an install script like this to users, you are welcome to ask on Discord in #software-pi or similar, but for now I'm going to have to revert these commits from the main repo.

**Comment by daniel-mrd-andersson** [comment]
> Hello,
> I used the new linux_install script today that worked so far
> but when I try a .hdf in the config I get this error
> 
> [PISCSI] Could not open PISCSI Boot ROM file for reading!
> 

An update to /etc/systemd/system/pistorm.service will fix this, change WorkingDirectory in that file to

WorkingDirectory=/usr/local/src/pistorm

**Pull request merged**
